### ISSUE TITLE
Terminal ignores $SHELL var

### ISSUE THREAD

**Issue by YannBrrd** [jupyterhub/sudospawner#20]
Hi,

When using Jupyterhub + sudospawner, $SHELL var looks ignored. I have users set with bash and shell launched is sh.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
