### ISSUE TITLE
User Server Will Not Restart

### ISSUE THREAD

**Issue by rghunter** [jupyterhub/sudospawner#6]
Hello, I have a user who appears to have gotten his server into a wierd state. From hub, whenever I click start server, I get the following message. When the user logs in, they get a screen that asks him to refresh his page when he clicks "my server".

![screen shot 2015-08-13 at 2 18 28 pm](https://cloud.githubusercontent.com/assets/448760/9257906/68c0eb38-41c6-11e5-824e-6f1ae625e36b.png)

**Comment by minrk** [comment]
Can you provide more logging information when this happens? The sudospawner is frustratingly difficult to debug, because it discards some output due to weird permissions issues.

**Comment by willingc** [comment]
I'm closing this issue as inactive. If anyone wishes to reopen, please leave a message in the comments. Thanks!
