### ISSUE TITLE
No publish to PyPI workflow setup

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/sudospawner#68]
There is no publish workflow setup for this project yet.

This is what we should add I think: https://github.com/jupyterhub/jupyterhub-idle-culler/blob/master/.github/workflows/publish.yml

@minrk @yuvipanda could you add jupyterhub-bot to https://pypi.org/project/sudospawner/? Then I'll setup a deployment token for this project and a GitHub secret named `PYPI_PASSWORD` like used in the workflow referenced above.

**Comment by minrk** [comment]
@consideRatio added the bot
